# Generated by Django 5.0 on 2025-01-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
