# Generated by Django 5.0 on 2024-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='championship_type',
            field=models.CharField(choices=[('bracket', 'Bracket'), ('points', 'Points')], default='points', max_length=20),
        ),
        migrations.AddField(
            model_name='championship',
            name='sport',
            field=models.CharField(default='soccer', max_length=50),
        ),
        migrations.AlterField(
            model_name='championship',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='championship',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
