# Generated by Django 5.0 on 2024-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0002_championship_championship_type_championship_sport_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='championships', to='teams.team'),
        ),
    ]
