# Generated by Django 5.0 on 2024-12-31 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0003_alter_championship_teams'),
        ('players', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='sport_type',
            field=models.CharField(choices=[('team', 'Team Sport'), ('individual', 'Individual Sport')], default='team', max_length=20),
        ),
        migrations.AlterField(
            model_name='championship',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChampionshipJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='championships.championship')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='championship_requests', to='players.playerprofile')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='teams.team')),
            ],
            options={
                'unique_together': {('championship', 'player')},
            },
        ),
    ]
