# Generated by Django 5.0 on 2025-01-03 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0005_alter_championship_sport'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='championships', to='sports.sport'),
        ),
    ]
