# Generated by Django 5.0 on 2025-01-05 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0006_alter_championship_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='sport_type',
        ),
    ]
