# Generated by Django 5.0 on 2025-01-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championships', '0007_remove_championship_sport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='is_active',
        ),
    ]
