# Generated by Django 5.0 on 2024-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('group', 'Group Stage'), ('quarter', 'Quarter Finals'), ('semi', 'Semi Finals'), ('final', 'Final')], default='group', max_length=20),
        ),
    ]
